// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbvz33Ioi-DyCvF8BBIud2jUJMatCUoeg',
    appId: '1:363949028736:web:2b11c43412a31ce5b53d65',
    messagingSenderId: '363949028736',
    projectId: 'pasteleria-ultrix',
    authDomain: 'pasteleria-ultrix.firebaseapp.com',
    databaseURL: 'https://pasteleria-ultrix-default-rtdb.firebaseio.com',
    storageBucket: 'pasteleria-ultrix.appspot.com',
    measurementId: 'G-4CK21BQW8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6a8HoTm2yw9hDFMcafKwii6yhoEhD5s0',
    appId: '1:363949028736:android:03e772daeabebe89b53d65',
    messagingSenderId: '363949028736',
    projectId: 'pasteleria-ultrix',
    databaseURL: 'https://pasteleria-ultrix-default-rtdb.firebaseio.com',
    storageBucket: 'pasteleria-ultrix.appspot.com',
  );
}
